# Generated by Django 5.2.17 on 2026-09-16 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apolice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condutorprincipal',
            name='segurado',
        ),
        migrations.AddField(
            model_name='condutorprincipal',
            name='apolice',
            field=models.OneToOneField(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='condutor_principal', to='apolice.apolice'),
            preserve_default=False,
        ),
    ]
